import os
import re
import argparse
import sys
import logging
from typing import Literal
from pydantic import BaseModel, Field
from google import genai
from google.genai import types
from google.genai.types import HttpOptions

# --- Logging Setup ---
logging.basicConfig(
    filename="coder_api_usage.log",
    level=logging.INFO,
    format="%(asctime)s - API CALL - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

API_CALL_COUNT = 0

def generate_with_tracking(client, model: str, contents: str, config, description: str):
    """Wrapper to track, log, and execute API calls."""
    global API_CALL_COUNT
    API_CALL_COUNT += 1
    log_msg = f"Call #{API_CALL_COUNT} | {description}"
    logging.info(log_msg)
    print(f"\n[API Tracker] {log_msg}...")
    
    return client.models.generate_content(
        model=model,
        contents=contents,
        config=config
    )

# --- Pydantic Schema for Iterative Planning ---
class FilePlan(BaseModel):
    filepath: str
    purpose: str
    action: Literal["create", "modify", "skip"] = Field(
        description="Must be 'create' for new files, 'modify' for files needing edits, or 'skip' if the file requires no changes."
    )

class ProjectArchitecture(BaseModel):
    files: list[FilePlan]

# 1. The Strict Formatting Contract
SYSTEM_INSTRUCTION = """
You are an expert autonomous coding agent. 
You must output perfectly formatted, complete code files.
Do not include any conversational text, explanations, or introductory filler. 

CRITICAL INSTRUCTION: ONLY generate <file> blocks for files that need to be CREATED or actively MODIFIED to fulfill the request. If an existing file does not require any changes, DO NOT output a <file> block for it.

NEVER generate or attempt to output lock files (like package-lock.json, yarn.lock, poetry.lock), dependency directories (like node_modules/), or large compiled/autogenerated files.

You MUST wrap every single file you generate using the following strict XML/Markdown hybrid structure:

<file name="relative/path/to/filename.ext">
```language
# Raw code goes here
```
</file>

If you generate multiple files, output them sequentially using this exact block structure.
"""

def extract_and_save_files(ai_response_text: str, output_dir: str = "generated_workspace", auto_save: bool = False):
    """
    Parses the AI's XML/Markdown hybrid output and writes the files to disk.
    """
    pattern = re.compile(r'<file name="([^"]+)">\s*```[^\n]*\n(.*?)\n```\s*</file>', re.DOTALL)
    
    matches = pattern.findall(ai_response_text)
    
    if not matches:
        print("Error: No files matching the strict XML schema were found in the response.")
        print("Raw response:\n", ai_response_text)
        return

    print(f"\nFound {len(matches)} file(s):")
    for filename, _ in matches:
        print(f"  - {filename}")

    if not auto_save:
        while True:
            try:
                choice = input("\nOptions: [p]review content, [s]ave files, [a]bort: ").strip().lower()
                if choice == 'p':
                    for filename, code in matches:
                        print(f"\n{'='*40}\nFILE: {filename}\n{'='*40}\n{code}\n")
                elif choice == 's':
                    break
                elif choice == 'a':
                    print("Aborted saving these files.")
                    return
                else:
                    print("Invalid choice. Please enter 'p', 's', or 'a'.")
            except EOFError:
                print("\nError: Interactive prompt failed because standard input was piped. Use '-y' to bypass prompts.")
                return

    print(f"Writing to './{output_dir}'...")

    for filename, code in matches:
        file_path = os.path.join(output_dir, filename)
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)
            
        print(f" -> Saved: {file_path}")

def generate_iteratively(client, prompt: str, output_dir: str, auto_save: bool):
    """
    Two-phase generation: plans the architecture first, then generates each file individually.
    """
    arch_config = types.GenerateContentConfig(
        temperature=0.2,
        response_mime_type="application/json",
        response_schema=ProjectArchitecture,
        system_instruction=(
            "You are a senior software architect. Given a project request and context, plan the necessary file modifications. "
            "For each file, provide the filepath, purpose, and the 'action' required. "
            "CRITICAL: Use 'skip' for any existing files in the context that do NOT need modifications. "
            "NEVER include lock files (e.g., package-lock.json) or dependency folders."
        )
    )
    
    try:
        arch_response = generate_with_tracking(
            client=client,
            model="gemini-2.5-flash",
            contents=prompt,
            config=arch_config,
            description="Phase 1: Planning Project Architecture"
        )
        architecture = arch_response.parsed
    except Exception as e:
        print(f"Failed to generate architecture: {e}")
        return

    print(f"[Phase 1 Complete] Planned {len(architecture.files)} files.\n")
    
    code_config = types.GenerateContentConfig(
        temperature=0.1,
        max_output_tokens=8192,
        system_instruction=SYSTEM_INSTRUCTION
    )

    print("[Phase 2] Generating Files...")
    accumulated_context = ""
    
    for file_plan in architecture.files:
        # Prevent generation if the architect deemed the file requires no changes
        if file_plan.action == "skip":
            print(f"  - Skipping '{file_plan.filepath}' (No changes required)")
            continue

        file_prompt = (
            f"Overall Project Context and Instructions: \n{prompt}\n\n"
            f"Task: Write the complete, runnable code for the file: '{file_plan.filepath}'.\n"
            f"Purpose of this file: {file_plan.purpose}\n"
            f"Action: {file_plan.action}\n"
        )
        
        if accumulated_context:
            file_prompt += f"\nCode already generated for this project that you can import/use:\n{accumulated_context}\n"
        
        try:
            file_response = generate_with_tracking(
                client=client,
                model="gemini-2.5-flash",
                contents=file_prompt,
                config=code_config,
                description=f"Phase 2: Generating {file_plan.filepath} ({file_plan.action})"
            )
            
            if file_response.candidates[0].finish_reason != 'STOP':
                print(f"    WARNING: {file_plan.filepath} generation cut off! Reason: {file_response.candidates[0].finish_reason}")
            
            extract_and_save_files(file_response.text, output_dir=output_dir, auto_save=auto_save)
            
            pattern = re.compile(r'<file name="([^"]+)">\s*```[^\n]*\n(.*?)\n```\s*</file>', re.DOTALL)
            matches = pattern.findall(file_response.text)
            for filename, code in matches:
                accumulated_context += f"\n--- {filename} ---\n{code}\n"
            
        except Exception as e:
            print(f"    Error generating {file_plan.filepath}: {e}")

def main():
    parser = argparse.ArgumentParser(description="Autonomous AI Coding Agent")
    parser.add_argument("prompt", help="The coding task for the AI to complete")
    parser.add_argument("--project", default=os.environ.get("GOOGLE_CLOUD_PROJECT", "coder-470"),
                        help="Google Cloud Project ID (defaults to GOOGLE_CLOUD_PROJECT env var)")
    parser.add_argument("--outdir", default="generated_workspace", 
                        help="The folder where generated files will be saved")
    parser.add_argument("--iterative", action="store_true", 
                        help="Enable iterative generation for massive projects")
    parser.add_argument("-y", "--yes", action="store_true",
                        help="Skip confirmation prompts and auto-save files")
    parser.add_argument("--context-file", 
                        help="Path to an exported codebase context file (e.g., from the 'context' CLI tool)")
    args = parser.parse_args()

    context_data = ""
    
    if args.context_file:
        try:
            with open(args.context_file, "r", encoding="utf-8") as f:
                context_data = f.read()
            print(f"Loaded {len(context_data)} bytes of context from {args.context_file}")
        except Exception as e:
            print(f"Error reading context file: {e}")
            sys.exit(1)
            
    elif not sys.stdin.isatty():
        context_data = sys.stdin.read()
        print(f"Loaded {len(context_data)} bytes of context from standard input.")
        if not args.yes:
            print("Notice: Piped input detected. Automatically enabling auto-save (-y) to prevent interactive prompt crash.")
            args.yes = True

    final_prompt = args.prompt
    if context_data:
        final_prompt = f"Here is the context of the existing codebase:\n\n{context_data}\n\nTask Instructions:\n{args.prompt}"

    try:
        client = genai.Client(
            vertexai=True,
            project=args.project,
            location="us-central1",
            http_options=HttpOptions(api_version="v1")
        )
    except Exception as e:
        print(f"Authentication Error: Could not initialize client. Are you logged into gcloud? \nDetails: {e}")
        sys.exit(1)

    config = types.GenerateContentConfig(
        temperature=0.1,
        max_output_tokens=8192,
        system_instruction=SYSTEM_INSTRUCTION
    )

    print(f"Generating code... (Target: ./{args.outdir}/)")
    
    if args.iterative:
        generate_iteratively(client, final_prompt, args.outdir, auto_save=args.yes)
    else:
        try:
            response = generate_with_tracking(
                client=client,
                model="gemini-2.5-flash",
                contents=final_prompt,
                config=config,
                description="Single-Shot File Generation"
            )
        except Exception as e:
            print(f"API Error: Request to Vertex AI failed. \nDetails: {e}")
            sys.exit(1)

        if response.candidates[0].finish_reason != 'STOP':
            print(f"WARNING: Generation did not finish normally! Reason: {response.candidates[0].finish_reason}")
            print("Attempting to parse whatever was generated so far...")
        
        extract_and_save_files(response.text, output_dir=args.outdir, auto_save=args.yes)

if __name__ == "__main__":
    main()
